### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by TheMikeGood** [jobec/rfc5424-logging-handler#1]
Hello!

Pip is throwing an error when I attempt to perform `pip install rfc5424-logging-handler`:

pip install rfc5424-logging-handler
Collecting rfc5424-logging-handler
  Downloading rfc5424-logging-handler-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Vm7mB5/rfc5424-logging-handler/setup.py", line 3, in <module>
        from rfc5424logging import __version__
      File "rfc5424logging/__init__.py", line 1, in <module>
        from .handler import Rfc5424SysLogHandler
      File "rfc5424logging/handler.py", line 37
    SyntaxError: Non-ASCII character '\xe2' in file rfc5424logging/handler.py on line 38, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Vm7mB5/rfc5424-logging-handler/

**Comment by TheMikeGood** [comment]
@jobec - Created #2 to address the issue, plus a Python 2.x compatibility issue Pycharm noticed. ;)

**Comment by jobec** [comment]
`Non-ASCII character '\xe2' in file rfc5424logging/handler.py`. Weird, where's that coming from...
Must have come from copying part of the sysloghandler class from python itself.

**Comment by TheMikeGood** [comment]
Yeah. Pycharm says it's in the desc under the __init__, but I wasn't able to find it. Some research indicated their could be a hidden character somewhere, but I couldn't find that either.

**Comment by TheMikeGood** [comment]
Also, without the coding it throws a "Byte literal contains characters > 255" on the block comment alongside the non-ASCII character warning.

**Comment by jobec** [comment]
Found it. It are the single quotes in the text. For example around for example `'/var/run/syslog'`

**Comment by jobec** [comment]
Fixed and along with some other changes put on pypi
