### ISSUE TITLE
rfc5424 handler stops logging when rsyslog is restarted

### ISSUE THREAD

**Issue by emailallau** [jobec/rfc5424-logging-handler#15]
Compared SysLogHandler with rfc5424 handler, observed SysLogHandler continues to log to syslog even when rsyslog is restarted, whereas rfc5424 handler fails to log when rsyslog is restarted with error "Transport endpoint is not connected"

**Comment by jobec** [comment]
Can you give me some example code showing how you configured things? Along with a traceback of the error.

**Comment by emailallau** [comment]
Sample script to simulate this issue
`import logging
import time
from rfc5424logging import Rfc5424SysLogHandler


rfc5424_logger = logging.getLogger(__name__)

rfc5424_log_handler = Rfc5424SysLogHandler(
                     address='/dev/log'
                    )
rfc5424_logger.addHandler(rfc5424_log_handler)

# Set level
rfc5424_logger.setLevel(logging.DEBUG)


i=1
while True:
   print "Logging..."
   rfc5424_logger.info("Hello MOhd here:rfc5424logger: %s" %str(i))
   i += 1
   time.sleep(1)`


Run this script and check logging in /var/log/syslog and restart rsyslog, we can observe logging gets stopped

**Comment by emailallau** [comment]
Error traceback
self.socket.send(syslog_msg)
error: [Errno 107] Transport endpoint is not connected
Logged from file test1.py, line 20

**Comment by jobec** [comment]
You have the full traceback? Like you see it on the console.
I'm mostly interested where it's being raised in the package.

**Comment by emailallau** [comment]
venv/lib/python2.7/site-packages/rfc5424logging/handler.py", line 340, in emit
    self.socket.send(syslog_msg)
error: [Errno 107] Transport endpoint is not connected
Logged from file test1.py, line 20

**Comment by emailallau** [comment]
Hope this helps

**Comment by emailallau** [comment]
Observed below line of code is responsible for this behaviour, below change will fix this issue
Current code of handler.py version 1.1.1:

            # Off it goes
            # Copied from SysLogHandler
            if self.unixsocket:
                try:
                    self.socket.send(syslog_msg)
                **except OSError:** . ----> Line responsible for this issue
                    self.socket.close()
                    self._connect_unixsocket(self.address)
                    self.socket.send(syslog_msg)
            elif self.socktype == socket.SOCK_DGRAM:
                self.socket.sendto(syslog_msg, self.address)
            else:
                self.socket.sendall(syslog_msg)
        except Exception:
            self.handleError(record)


New code change version required in 1.1.1:

             # Off it goes
            # Copied from SysLogHandler
            if self.unixsocket:
                try:
                    self.socket.send(syslog_msg)
                **except socket.error:** . ----> Code fix for this issue
                    self.socket.close()
                    self._connect_unixsocket(self.address)
                    self.socket.send(syslog_msg)
            elif self.socktype == socket.SOCK_DGRAM:
                self.socket.sendto(syslog_msg, self.address)
            else:
                self.socket.sendall(syslog_msg)
        except Exception:
            self.handleError(record)

**Comment by emailallau** [comment]
Any update on this issue? Does the fix looks okay

**Comment by emailallau** [comment]
Thanks for your time to look into this issue

**Comment by jobec** [comment]
Here's the positive response :)

The weird thing is that the code you point to, is the same as in [the official python source for 3.6](https://github.com/python/cpython/blob/3.6/Lib/logging/handlers.py#L937). And also, [the docs state](https://docs.python.org/3/library/socket.html#exceptions) that `socker.error` is the deprecated alias of `OSError` and all exceptions for socket are subclasses of `OSError`. So it should be the right exception to cache. 

- Can you reproduce this with the standard `SysLogHandler`?
- What's the exact python version you're using?

**Comment by jobec** [comment]
It's a python 2 specific issue it seems.

In python 3 I can not reproduce the same error and logging simply continues as soon as rsyslog starts again.
But indeed, with python 2 I get the same error as you:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rfc5424logging/handler.py", line 346, in emit
    self.socket.send(syslog_msg)
error: [Errno 107] Transport endpoint is not connected
```
As stated above, replacing `except OSError:` with `except socket.error:` won't do it. The fix is also catching `IOError` because `socker.error`  [is a subclass of IOError](https://docs.python.org/2/library/socket.html#socket.error)

**Comment by jobec** [comment]
Please try the last version from `master`. It should fix your issue.

Once you confirm, I'll issue a bugfix release.

**Comment by emailallau** [comment]
Thanks a lot for your time to look into this issue....Will check against
master and will update you on the same...

**Comment by emailallau** [comment]
Have validated your code fix in master, with my application, things looks good....

**Comment by jobec** [comment]
Released v1.1.2

**Comment by RubenDZ** [comment]
v1.1.2 is release on 2017/02/03 according to the change log.  We're 2018 already, time flies!

**Comment by jobec** [comment]
damn 😊
