### ISSUE TITLE
Add the possibility to log in UTC

### ISSUE THREAD

**Issue by ioggstream** [jobec/rfc5424-logging-handler#22]
## I wish

to configure the logger to use UTC, eg 2018-08-24T11:06:30.831710Z`

## notes

a datetime object can be converted via:
```
d.utcnow().isoformat() + "Z"
```

**Comment by jobec** [comment]
Maybe a stupid question, but do you want the current time to be used as if it were UTC? Or convert the current time in UTC?

What use case do you have in mind for this? Logging from a lot of sources in different timezones to a central destination?

One workaround could be to change your server's timezone to UTC, but that's maybe not an option for other reasons.

**Comment by ioggstream** [comment]
Hi @jobec and thanks for your reply!

- the time should be *converted* in UTC. The unix timestamp of the date should be preserved ;)

- ensuring application logs are consistent even if I don't have control of the servers (eg. kubernetes, openshift, ..)

- server time in UTC is the best choice, but I can't always access servers. I control the application though

Feel free to ask further questions.

**Comment by jobec** [comment]
This was implemented in 26a4cdb00a77d76f047bc14dccc91890195f6ab5

Could you test and let me know if it works as expected?

**Comment by jobec** [comment]
It's now also available in v1.2.1

https://pypi.org/project/rfc5424-logging-handler/1.2.1/

**Comment by ioggstream** [comment]
I'm adding the lib to a couple of apps but still didn't finish. I'll ping you as soon as I'm done.

Thanks a lot in the meantime!
R
