### ISSUE TITLE
rfc5424-logging-handler for syslog server on CentOS 7 to use with elasticsearch logstash 6.4.1

### ISSUE THREAD

**Issue by mreloysanchez** [jobec/rfc5424-logging-handler#24]
Hello everyone,

I'm trying to figure out how to use the rfc5424-logging-handler noted here: https://rfc5424-logging-handler.readthedocs.io/en/latest/basics.html  I have python on my CentOS 7 x64 VM and downloaded and installed pip-18.1 to be able to run the "pip install rfc5424-logging-handler" command, but I am receiving the following error either as "sudo pip install rfc5424-logging-handler" or if I run it as root: 

Collecting rfc5424-logging-handler
  Retrying (Retry(total=4, connect=None, read=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x27266d0>: Failed to establish a new connection: [Errno -2 Name or serice not known',)': /simple/rfc5424-logging-handler/

Above repeats with "total=3", "total=2", "total=1", "total=0".  Then:

Could not find a version that satisfies the requirement rfc5424-logging-handler (from versions: ) No matching distribution found for rfc5424-logging-handler

I am not able to connect to the Internet, as this system is disconnected per our corporate guidelines preventing me from putting the machine on the network.  I have searched online, but I can't seem to find the rfc5424-logging-handler file to import manually.  I think what I need may be here somewhere, but I am just scratching the surface with python so I'm not sure how to use the files provided if indeed what I need are here: https://github.com/jobec/rfc5424-logging-handler

Thank you for any help you can provide,

Eloy Sanchez

**Comment by jobec** [comment]
First, download all files for this package and all dependent packages from pypi https://pypi.org/

* rfc5424-logging-handler
* tzlocal
* pytz

You can then install the package like this:
```
pip install --no-index --find-links=/local/dir/ rfc5424-logging-handler
```
This way it will use the local folder for installing and resolving dependencies.

**Comment by mreloysanchez** [comment]
Thank you jobec,

I was able to get the noted package and dependencies installed.  

Eloy Sanchez
