### ISSUE TITLE
Logstash to Kibana/elasticsearch (v6.4.1) Connection Issue (dead ES instance)

### ISSUE THREAD

**Issue by mreloysanchez** [jobec/rfc5424-logging-handler#25]
Hello,

We have configured our logstash on one CentOS 7 VM per the following logstash-syslog.conf:

# This configuration file is used to pull syslog data into logstash.
input {
  tcp {
    port => 5000
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

output {
  elasticsearch {
	hosts => ["172.16.1.16:9200"]
	user => ""
	password => ""
	}
  stdout { codec => rubydebug }
}

However, when we run it as follows: sudo /usr/share/logstash/bin/logstash –f logstash-syslog.conf --path.settings /etc/logstash 

We receive this error that we cannot seem to get past:

Attempted to resurrect connection to dead ES instance, but got an error, {:url=>http://172.16.1.16:9200/, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>Elasticsearch Unreachable: [http://172.16.1.16:9200/][Manticore::SocketException] Connection refused”}

Looking on message boards, one way seems to be to create users, but this feature seems to require more than just a Basic license, which we are using at the moment as we are developing the system in the lab.  https://www.elastic.co/guide/en/logstash/6.4/ls-security.html 

Thank you for any advice on how to move forward,

Eloy Sanchez

**Comment by jobec** [comment]
Are you sure your elasticsearch daemon is actually running?
Try to get a standard “hello world” kind of setup working first, then move on to adding that kind of config.

**Comment by mreloysanchez** [comment]
Good morning jobec,

Yes, I verified by running "sudo /bin/systemctl status elasticsearch.service" on our elasticsearch server and it displays:

Loaded: loaded (usr/lib/system/system/elasticsearch.service; enabled; vendor preset: disabled)
Active: active (running) since 2018-10-08 20:13:54 GMT; 1 day 18h ago...

I also just performed the, "Stashing Your First Event" here: https://www.elastic.co/guide/en/logstash/current/first-event.html successfully to display the message, "hello world". I am receiving these messages though:

WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
Could not find log4j2 configuration at path /usr/share/logstash/config/log4j2.properties. Using default config which logs errors to the console
[WARN] 2018-10-10 14:32:02:035 [LogStash: :Runner] multilocal - Ignoring the 'pipelines.yml' file because modules or command line options are specified

Other than that, it did display, "Successfully started Logstash API endpoint {:port=>9601}

Your thoughts?

Thank you,

Eloy Sanchez

**Comment by jobec** [comment]
I'm afraid I'm by no means an elasticsearch expert.

I can help with logstash a bit, but for elasticsearch you'll be better of asking your question on stackoverflow and the like...

**Comment by mreloysanchez** [comment]
Thanks jobec,

You have helped me get past one hurdle.  I'll continue working through their tutorials in hopes of getting logstash to output our sylogs to elasticsearch/kibana.

Eloy Sanchez
