### ISSUE TITLE
Address resolution behaviour assumes IPv4+IPv6 listening

### ISSUE THREAD

**Issue by kaiw** [jobec/rfc5424-logging-handler#31]
In `TCPSocketTransport`, the `getaddrinfo` logic that resolves the remote syslog address assumes that a server will be listening to all returned 5-tuples. This breaks when, for example:
 * the syslog daemon is only listening on 127.0.0.1
 * the logging handler is configured to connect to e.g., `localhost`
 * `getaddrinfo` returns the corresponding IPv6 address first in the list (if it returns the IPv4 address first, everything will work just fine)

Depending on the intended behaviour, I think the easiest fix is probably to set `error = None` after https://github.com/jobec/rfc5424-logging-handler/blob/8f8a04542dfd01cb251f5afccf972218d3ec71b9/rfc5424logging/transport.py#L39

**Comment by jobec** [comment]
You're right. This is a subtle bug.

Fixed
